<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="11" passed="4" failed="1" skipped="6">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-10T13:07:35 IST" name="Default suite" finished-at="2024-10-10T13:07:55 IST" duration-ms="20288">
    <groups>
    </groups>
    <test started-at="2024-10-10T13:07:35 IST" name="Default test" finished-at="2024-10-10T13:07:55 IST" duration-ms="20288">
      <class name="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest">
        <test-method is-config="true" signature="setup(org.testng.ITestContext)[pri:0, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:35 IST" name="setup" finished-at="2024-10-10T13:07:38 IST" duration-ms="2898" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@5377414a]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="DoctorFacilityUserLoginTest()[pri:1, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:38 IST" name="DoctorFacilityUserLoginTest" finished-at="2024-10-10T13:07:40 IST" duration-ms="2538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DoctorFacilityUserLoginTest -->
        <test-method signature="clickonNewRequestTest()[pri:2, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:41 IST" name="clickonNewRequestTest" finished-at="2024-10-10T13:07:45 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.DoctorFacilityUserLoginTest" duration-ms="4405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonNewRequestTest -->
        <test-method signature="fetchorderidfromfile()[pri:3, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:45 IST" name="fetchorderidfromfile" finished-at="2024-10-10T13:07:45 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonNewRequestTest" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fetchorderidfromfile -->
        <test-method signature="clickonSearchoption()[pri:4, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:45 IST" name="clickonSearchoption" finished-at="2024-10-10T13:07:45 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.fetchorderidfromfile" duration-ms="140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonSearchoption -->
        <test-method signature="clickonOrderID()[pri:5, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:45 IST" name="clickonOrderID" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonSearchoption" duration-ms="10028" status="FAIL">
          <exception class="org.openqa.selenium.TimeoutException">
            <message>
              <![CDATA[Expected condition failed: waiting for visibility of element located by By.xpath: (//a[contains(@href,'/admin/document-request/')])[1] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.91 (b00bc8b76d60..., userDataDir: C:\Users\krish\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:53296}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:53296/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d0fc3b7d201850802d69d51904e9df8f]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: (//a[contains(@href,'/admin/document-request/')])[1] (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '4.19.1', revision: 'abe0ee07dc'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.6'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.90, chrome: {chromedriverVersion: 129.0.6668.91 (b00bc8b76d60..., userDataDir: C:\Users\krish\AppData\Loca...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:53296}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:53296/devtoo..., se:cdpVersion: 129.0.6668.90, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d0fc3b7d201850802d69d51904e9df8f
at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
at com.qa.OrderManagement.pages.DoctorFacilityHomePage.clickOrderid(DoctorFacilityHomePage.java:82)
at com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonOrderID(DoctorFacilityUserServerOrderTest.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.TimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonOrderID -->
        <test-method signature="fetchOrderID()[pri:6, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:55 IST" name="fetchOrderID" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonOrderID" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.fetchOrderID() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonOrderID() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.fetchOrderID() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonOrderID() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fetchOrderID -->
        <test-method signature="selectInternalstatusTest()[pri:7, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:55 IST" name="selectInternalstatusTest" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.fetchOrderID" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.selectInternalstatusTest() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.fetchOrderID() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.selectInternalstatusTest() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.fetchOrderID() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectInternalstatusTest -->
        <test-method signature="clickonfiletab()[pri:9, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:55 IST" name="clickonfiletab" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.updateOrderDetails" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonfiletab() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.updateOrderDetails() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonfiletab() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.updateOrderDetails() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonfiletab -->
        <test-method signature="updateOrderDetails()[pri:8, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:55 IST" name="updateOrderDetails" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.selectInternalstatusTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.updateOrderDetails() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.selectInternalstatusTest() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.updateOrderDetails() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.selectInternalstatusTest() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateOrderDetails -->
        <test-method signature="uploadbutton()[pri:10, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:55 IST" name="uploadbutton" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonfiletab" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.uploadbutton() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonfiletab() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.uploadbutton() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonfiletab() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadbutton -->
        <test-method signature="clickonbrowsefiles()[pri:11, instance:com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]" started-at="2024-10-10T13:07:55 IST" name="clickonbrowsefiles" finished-at="2024-10-10T13:07:55 IST" depends-on-methods="com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.uploadbutton" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonbrowsefiles() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.uploadbutton() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.clickonbrowsefiles() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca depends on not successfully finished methods 
[com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest.uploadbutton() on instance com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest@452e19ca]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickonbrowsefiles -->
      </class> <!-- com.qa.Ordermanagement.Test.DoctorFacilityUserServerOrderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
